package com.tbp.visao;

import com.tbp.modelo.*;
import com.tbp.repository.*;
import com.tbp.validacao.MagnusOpusValidacao;
import com.tbp.validacao.ArtistaValidacao;
import com.tbp.validacao.ProdutoraValidacao;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;


@Component
public class Janela extends javax.swing.JFrame {
    
    @Autowired
    private ArtistaRepository artistaRepository;
    @Autowired
    private MagnusOpusRepository magnusOpusRepository;
    @Autowired
    private ProdutoraRepository produtoraRepository;
    
    public Janela() {
        initComponents();  
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanel = new javax.swing.JTabbedPane();
        abaCadastroEmpresa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeArtista = new javax.swing.JTextField();
        genreArtista = new javax.swing.JTextField();
        botaoSalvarArtista = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        albumArtista1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        produtoraArtista = new javax.swing.JTextField();
        abaBuscar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campoBusca = new javax.swing.JTextField();
        painelResultados = new javax.swing.JScrollPane();
        botaoBuscar = new javax.swing.JButton();
        abaExibir = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoEditarId = new javax.swing.JTextField();
        campoEditarNome = new javax.swing.JTextField();
        comboEditarProdutora = new javax.swing.JComboBox<>();
        botaoEditarArtista = new javax.swing.JButton();
        botaoRemoverArtista = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        campoEditarGenero = new javax.swing.JTextField();
        exportarArtistasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabPanelMouseClicked(evt);
            }
        });

        jLabel1.setText("Gênero Musical:");

        jLabel2.setText("Nome:");

        nomeArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeArtistaActionPerformed(evt);
            }
        });

        genreArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreArtistaActionPerformed(evt);
            }
        });

        botaoSalvarArtista.setText("Salvar");
        botaoSalvarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarArtistaActionPerformed(evt);
            }
        });

        jLabel13.setText("Magnus Opus:");

        albumArtista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumArtista1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Produtora:");

        produtoraArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produtoraArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaCadastroEmpresaLayout = new javax.swing.GroupLayout(abaCadastroEmpresa);
        abaCadastroEmpresa.setLayout(abaCadastroEmpresaLayout);
        abaCadastroEmpresaLayout.setHorizontalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                            .addComponent(genreArtista)
                            .addComponent(albumArtista1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(produtoraArtista)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaCadastroEmpresaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoSalvarArtista)))
                .addContainerGap())
        );
        abaCadastroEmpresaLayout.setVerticalGroup(
            abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaCadastroEmpresaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomeArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(genreArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(albumArtista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaCadastroEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(produtoraArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(botaoSalvarArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPanel.addTab("Cadastrar Artista", abaCadastroEmpresa);

        abaBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                abaBuscarFocusGained(evt);
            }
        });

        jLabel7.setText("Busca:");

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });

        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaBuscarLayout = new javax.swing.GroupLayout(abaBuscar);
        abaBuscar.setLayout(abaBuscarLayout);
        abaBuscarLayout.setHorizontalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        abaBuscarLayout.setVerticalGroup(
            abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaBuscarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(abaBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addGap(34, 34, 34)
                .addComponent(painelResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        tabPanel.addTab("Buscar Artista", abaBuscar);

        jLabel8.setText("ID");

        jLabel9.setText("Nome:");

        jLabel12.setText("Produtora");

        campoEditarId.setEditable(false);

        comboEditarProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEditarProdutoraActionPerformed(evt);
            }
        });

        botaoEditarArtista.setText("Editar");
        botaoEditarArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarArtistaActionPerformed(evt);
            }
        });

        botaoRemoverArtista.setText("Remover");
        botaoRemoverArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverArtistaActionPerformed(evt);
            }
        });

        jLabel11.setText("Gênero:");

        exportarArtistasButton.setText("Exportar");
        exportarArtistasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarArtistasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaExibirLayout = new javax.swing.GroupLayout(abaExibir);
        abaExibir.setLayout(abaExibirLayout);
        abaExibirLayout.setHorizontalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, abaExibirLayout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(exportarArtistasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEditarArtista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoRemoverArtista)
                .addGap(154, 154, 154))
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(53, 53, 53)
                        .addComponent(comboEditarProdutora, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(66, 66, 66)
                        .addComponent(campoEditarGenero))
                    .addGroup(abaExibirLayout.createSequentialGroup()
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(73, 73, 73)
                        .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEditarNome)
                            .addComponent(campoEditarId, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        abaExibirLayout.setVerticalGroup(
            abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaExibirLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoEditarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoEditarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoEditarGenero)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(comboEditarProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(abaExibirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditarArtista)
                    .addComponent(botaoRemoverArtista)
                    .addComponent(exportarArtistasButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabPanel.addTab("Exibir Artista", abaExibir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabPanelMouseClicked
        Iterable<Produtora> produtoras = produtoraRepository.findAll();
        comboEditarProdutora.removeAllItems();
        for(Produtora produtora : produtoras) {
            comboEditarProdutora.addItem(produtora);
        }
    }//GEN-LAST:event_tabPanelMouseClicked

    private void botaoRemoverArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverArtistaActionPerformed
        try {
        Integer id = Integer.parseInt(campoEditarId.getText());
        magnusOpusRepository.deleteById(id);
        artistaRepository.deleteById(id);
        JOptionPane.showMessageDialog(null, "Artista removido com sucesso");
        tabPanel.setSelectedComponent(abaBuscar);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_botaoRemoverArtistaActionPerformed

    private void botaoEditarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarArtistaActionPerformed
        try {
        Integer id = Integer.parseInt(campoEditarId.getText());
        String nome = campoEditarNome.getText();
        String genero = campoEditarGenero.getText();
        Produtora produtora = (Produtora) comboEditarProdutora.getSelectedItem();
        Artista artista = new Artista(nome, genero, produtora);
        artista.setId(id);
        artistaRepository.save(artista);
        JOptionPane.showMessageDialog(null, "Artista atualizado com sucesso.");
        tabPanel.setSelectedComponent(abaBuscar);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_botaoEditarArtistaActionPerformed

    private void abaBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_abaBuscarFocusGained

    }//GEN-LAST:event_abaBuscarFocusGained

    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String nomeBuscar = campoBusca.getText();
        List<Artista> artistaList = artistaRepository.findByNomeIgnoreCaseContaining(nomeBuscar);
        JList jlist = new JList();
        DefaultListModel<Artista> model = new DefaultListModel();
        for(Artista artista : artistaList) {
            model.addElement(artista);
        }
        jlist.setModel(model);
        painelResultados.setViewportView(jlist);
        painelResultados.setVisible(true);
        
        jlist.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                Artista a = (Artista) jlist.getSelectedValue();
                campoEditarId.setText(a.getId().toString());
                campoEditarNome.setText(a.getNome());
                campoEditarGenero.setText(a.getGenero());
                
                Iterable<Produtora> produtoras = produtoraRepository.findAll();
                for(Produtora produtora : produtoras) {
                    comboEditarProdutora.addItem(produtora);
                    if(produtora.getId().equals(a.getProdutora().getId())) {
                        comboEditarProdutora.setSelectedItem(produtora);
                    }
                }
                tabPanel.setSelectedComponent(abaExibir);
                model.clear();
            }
        });
        
    }//GEN-LAST:event_botaoBuscarActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void produtoraArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produtoraArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_produtoraArtistaActionPerformed

    private void albumArtista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumArtista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_albumArtista1ActionPerformed

    private void botaoSalvarArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarArtistaActionPerformed
        MagnusOpusValidacao magnusopusValidacao = new MagnusOpusValidacao();
        ArtistaValidacao artistaValidacao = new ArtistaValidacao();
        ProdutoraValidacao produtoraValidacao = new ProdutoraValidacao();

        String nome = nomeArtista.getText();
        String genero = genreArtista.getText();
        String nomeAlbum = albumArtista1.getText();
        String produtoraNome = produtoraArtista.getText();
        

        try {
            Produtora produtora = new Produtora(produtoraNome);
            Artista artista = new Artista(nome, genero, produtora);
            MagnusOpus magnusopus = new MagnusOpus(nomeAlbum, artista);

            artistaValidacao.validarArtista(artista);
            produtoraValidacao.validarProdutora(produtora);
            magnusopusValidacao.validarMagnusOpus(magnusopus);
            
            produtoraRepository.save(produtora);
            artistaRepository.save(artista);
            magnusOpusRepository.save(magnusopus);
            

            JOptionPane.showMessageDialog(null, "Artista salvo com sucesso. ");
            nomeArtista.setText("");
            genreArtista.setText("");
            albumArtista1.setText("");
            produtoraArtista.setText("");
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            nomeArtista.setText("");
            genreArtista.setText("");
            albumArtista1.setText("");
            produtoraArtista.setText("");
        }
    }//GEN-LAST:event_botaoSalvarArtistaActionPerformed

    private void genreArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreArtistaActionPerformed

    private void nomeArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeArtistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeArtistaActionPerformed

    private void comboEditarProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEditarProdutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEditarProdutoraActionPerformed

    private void exportarArtistasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarArtistasButtonActionPerformed
        Iterable<Artista> artistas = artistaRepository.findAll();
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fileChooser.showSaveDialog(null);
            
            File file = new File(fileChooser.getSelectedFile(), "artistas.csv");
            System.out.println(file.getAbsolutePath());
            FileWriter fileWriter = new FileWriter(file, false);
            StringBuffer buffer = new StringBuffer();
            for(Artista artista : artistas) {
                buffer.append(artista.getId());
                buffer.append(";");
                buffer.append(artista.getNome());
                buffer.append(";");
                buffer.append(artista.getGenero());
                buffer.append(";");
                buffer.append(artista.getProdutora().getNome());
                buffer.append(";");
                buffer.append("\n");
            }
            String texto = buffer.toString();
            fileWriter.append(texto);
            fileWriter.flush();
            fileWriter.close();
        } catch(IOException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_exportarArtistasButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaBuscar;
    private javax.swing.JPanel abaCadastroEmpresa;
    private javax.swing.JPanel abaExibir;
    private javax.swing.JTextField albumArtista1;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoEditarArtista;
    private javax.swing.JButton botaoRemoverArtista;
    private javax.swing.JButton botaoSalvarArtista;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JTextField campoEditarGenero;
    private javax.swing.JTextField campoEditarId;
    private javax.swing.JTextField campoEditarNome;
    private javax.swing.JComboBox<Produtora> comboEditarProdutora;
    private javax.swing.JButton exportarArtistasButton;
    private javax.swing.JTextField genreArtista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeArtista;
    private javax.swing.JScrollPane painelResultados;
    private javax.swing.JTextField produtoraArtista;
    private javax.swing.JTabbedPane tabPanel;
    // End of variables declaration//GEN-END:variables
}
